spring.application.name=wj-sample

##주현 추가 Prometheus 모니터링 설정
management.endpoints.web.exposure.include=*
# management.endpoint.metrics.enabled=true
# management.endpoints.enabled-by-default=true
# management.metrics.export.prometheus.enabled=true